name: CI test

on: issue_comment

jobs:
  ci:
    name: ci
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/train') }}

    runs-on: ubuntu-latest
    steps:
      - name: GET branch
        id: get-branch
        run: |
          pr_number=${{ github.event.issue.number }}
          repo=${{ github.repository }}
          api_url="https://api.github.com/repos/$repo/pulls/$pr_number"
          branch=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url | jq -r .head.ref)
          echo "branch=$branch" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
      - name: Echo
        run: echo "Branch: ${{ env.branch }}"
