name: CI test

on: issue_comment

jobs:
  ci:
    name: ci
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/train') }}
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: GET branch
        id: get-branch
        run: |
          branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
          echo "branch=$branch" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}

