name: CI test

on: issue_comment

jobs:
  ci:
    if: ${{ github.event.issue.pull_request  && startsWith(github.event.comment.body, '/train') }}
    runs-on: ubuntu-latest
    steps:
      - id: 'get-branch'
	run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
	env:
	  REPO: ${{ github.repository }}
	  PR_NO: ${{ github.event.issue.number }}
	  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
	uses: actions/checkout@v2
	with:
	  ref: ${{ steps.get-branch.outputs.branch }}

      - name: echo
        run: echo ${{ steps.get-branch.outputs.branch }}
